/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fanao_daoshuri_ndkprotect_LittleWidgetWatcher */

#ifndef _Included_com_fanao_daoshuri_ndkprotect_LittleWidgetWatcher
#define _Included_com_fanao_daoshuri_ndkprotect_LittleWidgetWatcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fanao_daoshuri_ndkprotect_LittleWidgetWatcher
 * Method:    openLittleWidgetWatcher
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_fanao_daoshuri_ndkprotect_LittleWidgetWatcher_openLittleWidgetWatcher
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
